# Generated by Django 4.2.4 on 2023-08-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Noutbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noutbook_price', models.IntegerField(default=0)),
            ],
        ),
    ]
